<?php
/**
 * Created by PhpStorm.
 * User: alejandro.gomez
 * Date: 06/01/2017
 * Time: 01:07 PM
 */
?>
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- sidebar menu: : style can be found in sidebar.less -->

        <ul class="sidebar-menu">
            <li class="active"><a href="#"onclick="location.reload()"><i class="ion ion-ios-home"></i> <span>Inicio</span></a></li>
            <li><a href="#" onclick="getMenu(4,4)"><i class="ion ion-pricetags"></i> <span>Compras</span><i class="fa fa-caret-right pull-right"></i> </a></li>
            <li><a href="#" onclick="getMenu(5,5)"><i class="ion ion-ios-list  "></i> <span>Inventario</span><i class="fa fa-caret-right pull-right"></i> </a></li>
            <li><a href="#" onclick="getMenu(8,8)"><i class="ion ion-android-restaurant  "></i> <span>Platillos</span><i class="fa fa-caret-right pull-right"></i> </a></li>
            <li><a href="#" onclick="getMenu(3,3)"><i class="ion ion-social-usd  "></i> <span>Ventas</span><i class="fa fa-caret-right pull-right"></i> </a></li>
            <li><a href="#" onclick="getMenu(6,6)"><i class="ion ion-pie-graph  "></i> <span>Reportes</span><i class="fa fa-caret-right pull-right"></i> </a></li>
            <li><a href="#" onclick="getMenu(7,7)"><i class="ion ion-settings  "></i> <span>Configuración</span><i class="fa fa-caret-right pull-right"></i> </a></li>
            <li><a href="#" onclick="getMenu(2,2)"><i class="ion ion-android-exit text-red"></i><span>Salir</span><i class="fa fa-close text-red pull-right"></i></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>
$350